-- AlterTable
ALTER TABLE "UserProfile" ADD COLUMN "proteinGoal" DOUBLE PRECISION,
ADD COLUMN "carbGoal" DOUBLE PRECISION,
ADD COLUMN "fatGoal" DOUBLE PRECISION,
ADD COLUMN "energyGoal" DOUBLE PRECISION;